version: '3.7'

services:

  consul-init-certs:
    image: hashicorp/consul:1.22.2
    working_dir: /consul/config/certs 
    volumes:
      - ./certs/:/consul/config/certs/
    entrypoint: sh
    command: >
          -c "
          rm -f /consul/config/certs/*.pem &&
          /bin/consul tls ca create &&
          /bin/consul tls cert create -server -dc dc1
          "
  consul-server1:
    image: hashicorp/consul-enterprise:1.22.2-ent
    container_name: consul-server1
    restart: always
    depends_on:
      consul-init-certs:
        condition: service_completed_successfully
    volumes:
     - ./server1.hcl:/consul/config/server1.hcl
     - ./acl.hcl:/consul/config/acl.hcl
     - ./certs/:/consul/config/certs/
     - ./license.hclic:/consul/config/license.hclic
    networks:
      - consul
    ports:
      - "8500:8500"
      - "8501:8501"
      - "8600:8600/tcp"
      - "8600:8600/udp"
    command: "agent -bootstrap-expect=3"

  consul-server2:
    image: hashicorp/consul-enterprise:1.22.2-ent
    container_name: consul-server2
    restart: always
    depends_on:
      consul-init-certs:
        condition: service_completed_successfully
    volumes:
     - ./server2.hcl:/consul/config/server2.hcl
     - ./acl.hcl:/consul/config/acl.hcl
     - ./certs/:/consul/config/certs/
     - ./license.hclic:/consul/config/license.hclic
    networks:
      - consul
    command: "agent -bootstrap-expect=3"

  consul-server3:
    image: hashicorp/consul-enterprise:1.22.2-ent
    container_name: consul-server3
    restart: always
    depends_on:
      consul-init-certs:
        condition: service_completed_successfully
    volumes:
     - ./server3.hcl:/consul/config/server3.hcl
     - ./acl.hcl:/consul/config/acl.hcl
     - ./certs/:/consul/config/certs/
     - ./license.hclic:/consul/config/license.hclic
    networks:
      - consul
    command: "agent -bootstrap-expect=3"

  consul-client1:
    image: hashicorp/consul-enterprise:1.22.2-ent
    container_name: consul-client1
    restart: always
    depends_on:
      consul-init-certs:
        condition: service_completed_successfully
    volumes:
     - ./client1.hcl:/consul/config/client1.hcl
     - ./acl.hcl:/consul/config/acl.hcl
     - ./certs/:/consul/config/certs/
    networks:
      - consul
    command: "agent"

networks:
  consul:
    driver: bridge

